name: Workflow Triggered by repository_dispatch

on:
  repository_dispatch:
    types: [test-event]

jobs:
  echo-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository (optional but often required)

      - name: Echo dispatch success message
        run: |
          echo "Dispatch was successful!" && sleep 120

